### ISSUE TITLE
Item model 的设计

### ISSUE THREAD

**Issue by bmeritter** [MHwishes/201-nodejs-web#2]
1. id 的作用是什么？
2. categoryId 只是一个 String，没有表明 Item 和 Category 之间多对多的关系

**Comment by MHwishes** [comment]
。。。id貌似没啥实质的作用。。。

**Comment by MHwishes** [comment]
1.。。。id貌似没啥用。。。
2.确实是，在Item的model中不能说明item 和category的关系，我在想想，谢谢指出
